# DataBase Plugin Configuration
# Configuration for the DataBase plugin

database:
  # Database type: sqlite, mysql, postgresql
  type: "sqlite"
  
  # SQLite specific settings
  sqlite:
    # Database file path (relative to plugin folder)
    file: "database.db"
    # Enable WAL mode for better performance
    wal_mode: true
    # Connection timeout in seconds
    timeout: 30
  
  # MySQL/PostgreSQL settings (for future use)
  mysql:
    host: "localhost"
    port: 3306
    database: "minecraft"
    username: "root"
    password: ""
    ssl: false
    
  # Connection pool settings
  pool:
    # Maximum number of connections in pool
    max_connections: 10
    # Minimum number of connections in pool
    min_connections: 2
    # Connection timeout in milliseconds
    connection_timeout: 30000
    # Maximum lifetime of connection in milliseconds
    max_lifetime: 1800000
    # Idle timeout in milliseconds
    idle_timeout: 600000

# Logging configuration
logging:
  # Log level: DEBUG, INFO, WARN, ERROR
  level: "INFO"
  # Enable debug mode for detailed logging
  debug: false
  # Log database queries (for debugging)
  log_queries: false

# Performance settings
performance:
  # Enable async database operations
  async_operations: true
  # Batch size for bulk operations
  batch_size: 100
  # Cache settings
  cache:
    enabled: true
    # Cache size (number of entries)
    size: 1000
    # Cache expiration time in minutes
    expiration: 30

# Feature toggles
features:
  # Enable automatic database migrations
  auto_migrate: true
  # Enable database health checks
  health_checks: true
  # Enable metrics collection
  metrics: false